### ISSUE TITLE
Wrong gateway

### ISSUE THREAD

**Issue by fkooman** [pia-foss/tunnel-apple#63]
https://github.com/pia-foss/tunnel-apple/blob/bc08896820c793d6368369be0bd5a581c3baa3e9/PIATunnel/Sources/Core/PushReply.swift#L83

The second part of the `ifconfig` `PUSH_REPLY` is not the `gatewayAddress`, but the netmask of the IP to be assigned to the "tun" adapter.

For the gateway you have to look at the `route-gateway` `PUSH_REPLY`.

**Comment by fkooman** [comment]
This is in the `develop` branch by the way.

**Comment by fkooman** [comment]
It seems in the `master` branch it also worked more or less like this. I'm confused how this could have ever worked... :)

**Comment by keeshux** [comment]
@fkooman I admit I noticed it myself long time ago, but didn't dare to change it. I suspect it may cause gw issues as I face them with my own VPS, but never took the time to test (e.g. connected with data flowing, yet no Internet). I will definitely try the correct parsing now that you ask. To some extent, this may not have been harmful due to the obscure operation of NE routing settings. I remember tweaking them a lot and IIRC other nonsense setups would work regardless.

The back story is that the library was originally a 1:1 port from another language, so I merely translated that part while still wondering the same. I didn't question much back then but afterwards it just fell into the cracks of lazyness. If I tread lightly, it's just because this code has worked in production (PIA client for iOS) for several months. Again, NE is often *very* obscure.

**Comment by fkooman** [comment]
I actually have a patch that deals with this better (e.g. detects if `topology` is `subnet`, but I'm unable to get any traffic over the VPN with my current version based on `develop`... Not sure what is going on. The current `develop` works for you?

**Comment by keeshux** [comment]
Uhm, I think I've never touched that part again since 2017. Are you sure it's a routing problem? What do the logs suggest?

**Comment by fkooman** [comment]
Is there a way to get the app log to Xcode? The iPod touch is really too small to be able to get anything meaningful in that little window, and manually copy/pasting would take hours due to the amount of text there...

**Comment by fkooman** [comment]
This is my commit for attempting to deal with this. I can't test it myself currently: https://github.com/fkooman/tunnel-apple/commit/c54998e608a398cc8e433b4f109ebb211e93675c

**Comment by keeshux** [comment]
@fkooman open the Console macOS app and select the device running the app from the left column. You can then filter the relevant output by app name (e.g. "BasicTunnel").

**Comment by fkooman** [comment]
@keeshux https://gist.github.com/fkooman/127ee040749b895a734df500bc6936c5

There are some errors about the tunnel being dropped and then restarted. I can also see that on the iPod, the VPN icon in the top bar disappears for a second. Don't think this happened with the master branch.

The difference between what I run and develop: https://github.com/pia-foss/tunnel-apple/compare/develop...fkooman:vpn.tuxed.net

**Comment by keeshux** [comment]
@fkooman given that the errors I see in the log are coming from a crypto algorithm mismatch, you should ensure that client and server are agreeing on the same algorithms (observe the server log for comparison). You'd better disable NCP too, as server-side support is mostly broken.

**Comment by fkooman** [comment]
Strange that it *does* work with `master`, but not with `develop`...

**Comment by fkooman** [comment]
This issue was solved in https://github.com/pia-foss/tunnel-apple/commit/035949535f5eed003855456173fbbf7f1bb84c6d
